name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: The new version to build and publish
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git Identity
        run: |
          git config --global user.name "Customer.io"
          git config --global user.email "win@customer.io"

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Bump core
        run: |
          cd packages/core
          yarn version ${{ github.event.inputs.version }}

      - name: Bump browser
        run: |
          cd packages/browser
          yarn version ${{ github.event.inputs.version }}
          yarn run build-prep

      - name: Bump node
        run: |
          cd packages/node
          yarn version ${{ github.event.inputs.version }}

      - name: Push changes
        run: |
          git commit -am "Update version"
          git push
